version: '3'
services:
    wert-frontend:
        build:
            context: .
            dockerfile: docker/Dockerfile
        image: wert-frontend
        container_name: wert-frontend
        restart: unless-stopped
        ports:
            - 3000:3000

